name: "Jonny Burch"
aftername: "has been known do"
description: "Things I do when I'm doing things I'm not meant to be doing"

author: "Jonny Burch"

url: "http://jonnyburch.github.io"
baseurl: http://jonnyburch.github.io

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: 
ga_tracking_id:
